# .prettierrc or .prettierrc.yaml
trailingComma: "es5"
useTabs: false
tabWidth: 2
semi: false
singleQuote: true
arrowParens: avoid
bracketSpacing: false
printWidth: 80
packageManager: yarn
useEditorConfig: true